apiVersion: v1
kind: Pod
metadata:
  name: stock-api
  labels:
    app: stock-api

spec:
  containers:
  - name: stock-api
    image: mpriv32/stockapi:latest
    envFrom:
    - secretRef:
        name: api-credentials
  restartPolicy: Never
